// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRwS3rQ28Q_slYvwcf06iDaHtDlGey98E',
    appId: '1:577946224206:android:4556da5c46586e50d3651f',
    messagingSenderId: '577946224206',
    projectId: 'fire-chat-9b53f',
    databaseURL: 'https://fire-chat-9b53f.firebaseio.com',
    storageBucket: 'fire-chat-9b53f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8hmJ9izIMnA0FwZtijdnyErnaAF7sEkc',
    appId: '1:577946224206:ios:2fad074d5416f913d3651f',
    messagingSenderId: '577946224206',
    projectId: 'fire-chat-9b53f',
    databaseURL: 'https://fire-chat-9b53f.firebaseio.com',
    storageBucket: 'fire-chat-9b53f.appspot.com',
    iosClientId: '577946224206-n4pqe3hjdd50s1rnjpbivaffr7qls2q2.apps.googleusercontent.com',
    iosBundleId: 'com.itluobo.flashchat',
  );
}
